spring.application.name=booking-app

spring.datasource.url=jdbc:mysql://localhost:3306/comp4442
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
